const List<String> englishReciters = [
  "Ahmed Al-Hudhaify",
  "Ahmed Deban",
  "Ahmed Al-Tarabulsi",
  "Ahmed bin Ali Al-Ajmi",
  "Ahmed Talib Hameed",
  "Ahmed Mohammed Taher",
  "Ahmed Khalil Shahin",
  "Ahmed Eissa Al-Ma'sarawi",
  "Ahmed Al-Lahdan",
  "Ahmed Al-Nafees",
  "Ahmed Nu'ain",
  "Ahmed Nasr",
  "Ahmed Mohammed Amer",
  "Ahmed Al-Sa'eed Mandoor",
  "Ahmed Al-Shafi'i",
  "Ahmed Khader Ibrahim Al-Akhdar",
  "Ibrahim Al-Jibrin",
  "Ibrahim Al-Asiri",
  "Idris Abkar",
  "Adham Al-Nabulsi",
  "Ishaq Danish",
  "Islam Sobhi",
  "Akram Al-Allaqmi",
  "Ilhan Tok",
  "Anas Barraq",
  "Anas Jahloum",
  "Anas Al-Emadi",
  "Anas Al-Maiman",
  "Anas Mohammed",
  "Elias Hijry",
  "Al-Amin Mohammed Qunwa",
  "Ayman Swaid"
];